In [1]:
import numpy as np

#### 返回index

In [2]:
np.unravel_index(78,(6,7,3))

(3, 5, 0)

#### checkerborar

In [8]:
A = np.eye(3)
np.tile(A,(2,3))

array([[1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.]])

#### Normalize

In [11]:
Z = np.random.random((5,5))
Z = (Z-np.mean(Z))/(np.std(Z))
Z

array([[ 0.20463208, -1.19058237,  1.21685236, -0.90429741, -1.06105122],
       [ 1.55692869,  1.13427275,  1.08030945, -1.50909599, -1.29686516],
       [ 1.12108864, -1.5282497 , -0.00828893,  0.69319073, -0.46012293],
       [ 0.60080468,  0.41020921,  0.25915617, -0.89973314,  0.50762693],
       [ 0.93015432, -0.74576327,  0.01982726,  1.33106841, -1.46207156]])

#### RGBA

In [14]:
color = np.dtype([('r',np.ubyte,1),
                 ('g',np.ubyte,1),
                 ('b',np.ubyte,1),
                 ('a',np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

##### 3X2 to 5X3

In [17]:
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [19]:
np.ones((5,3))@np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 重新赋值

In [22]:
Z = np.arange(28)
Z[(Z>8) & (Z<20)] *= -1
Z

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15, -16, -17, -18, -19,  20,  21,  22,  23,  24,  25,
        26,  27])

In [28]:
import numpy as np
sum(range(5),-1)

10

In [29]:
from numpy import *
sum(range(5),-1)

10

#### 什么意思

In [34]:
Z = np.arange(10)
Z**Z  # [i**i for i in Z]

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [40]:
Z<<Z>>Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a = np.array([0,4,9,16,25])
a<<a>>a

array([ 0,  4,  9, 16, 25])

In [44]:
a <- a

array([False, False, False, False, False])

In [50]:
Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
a < a > a

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [55]:
np.array(0)/np.array(0)

/Users/lemo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [56]:
np.array(0)//np.array(0)

/Users/lemo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [59]:
np.array([np.nan])

array([nan])

In [60]:
np.array([np.nan]).astype(int)

array([-9223372036854775808])

In [61]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [62]:
Z = np.random.uniform(-10,+10,10)
Z

array([-9.40198616, -8.28212256, -6.04219387, -7.14634498,  9.99018662,
        4.52104109,  3.20851242, -8.30445402,  4.22686201, -0.89317729])

In [66]:
np.ceil(np.abs(Z))

array([10.,  9.,  7.,  8., 10.,  5.,  4.,  9.,  5.,  1.])

In [67]:
np.copysign(np.ceil(np.abs(Z)),Z)

array([-10.,  -9.,  -7.,  -8.,  10.,   5.,   4.,  -9.,   5.,  -1.])

#### common values

In [74]:
np.random.seed(10)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
np.intersect1d(Z1,Z2)

[9 4 0 1 9 0 1 8 9 0]
[8 6 4 3 0 4 6 8 1 8]


array([0, 1, 4, 8])

#### ignore all warnings

In [87]:
defaults = np.seterr(all = 'ignore')

In [88]:
Z = np.ones(1)/0
Z

array([inf])

In [89]:
_ = np.seterr(**defaults)
np.ones(1)/0

/Users/lemo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([inf])

In [83]:
with np.errstate(divide = 'ignore'):
    Z = np.ones(1)/0
    print(Z)

[inf]


In [90]:
np.sqrt(-1)

/Users/lemo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [91]:
np.emath.sqrt(-1)

1j

In [92]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/lemo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### date

In [94]:
np.datetime64('today','D') - np.timedelta64(1,'D')

numpy.datetime64('2019-08-17')

In [95]:
np.datetime64('today','D')

numpy.datetime64('2019-08-18')

In [98]:
np.datetime64('today','D') + np.timedelta64(1,'D')

numpy.datetime64('2019-08-19')

In [96]:
np.datetime64('today','M')

numpy.datetime64('2019-08')

In [97]:
np.datetime64('today','Y')

numpy.datetime64('2019')

In [99]:
np.arange('2016-07','2016-08',dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

####  计算

In [102]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

In [103]:
np.add(A,B,out = B)

array([3., 3., 3.])

In [105]:
B

array([3., 3., 3.])

In [106]:
np.divide(A,2,out = A)
A

array([0.5, 0.5, 0.5])

In [107]:
np.negative(A,out = A)

array([-0.5, -0.5, -0.5])

In [109]:
np.multiply(A,B,out = B)

array([-1.5, -1.5, -1.5])

In [110]:
B

array([-1.5, -1.5, -1.5])

####  boardcasting

In [111]:
Z = np.zeros(5)
Z += np.arange(5)
Z

array([0., 1., 2., 3., 4.])

In [113]:
Z = np.random.uniform(0,10,10)
Z

array([5.9758229 , 8.7239246 , 9.83020867, 4.67403279, 8.75744495,
       2.96068699, 1.31291053, 8.42817933, 6.59036304, 5.95439605])

In [131]:
%%timeit
np.ceil(Z)-1

1.48 µs ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [132]:
%%timeit
Z.astype(int)

385 ns ± 14 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [133]:
%%timeit
Z - Z%1

1.81 µs ± 32.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [134]:
%%timeit
np.floor(Z)

490 ns ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [130]:
%%timeit
np.trunc(Z)

489 ns ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 生成i器

In [135]:
def generate():
    for x in range(10):
        yield x

In [137]:
%%timeit
Z = np.fromiter(generate(),dtype = float,count = -1)

2.5 µs ± 99.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [139]:
%%timeit
np.arange(10)

468 ns ± 6.99 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [144]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [147]:
Z = np.random.random(10)
print(Z)
Z.sort()
print(Z)

[0.23264106 0.55651819 0.52381088 0.35095822 0.70533161 0.82070374
 0.134563   0.60472616 0.28314828 0.50640782]
[0.134563   0.23264106 0.28314828 0.35095822 0.50640782 0.52381088
 0.55651819 0.60472616 0.70533161 0.82070374]


#### faster

In [148]:
%%timeit
np.sum(np.arange(10))

3.46 µs ± 190 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [149]:
%%timeit
np.add.reduce(np.arange(10))

1.72 µs ± 52.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [151]:
?np.add.reduce

####  equal or allclose

In [152]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [155]:
A

array([0, 0, 0, 0, 1])

In [156]:
B

array([0, 1, 1, 1, 0])

In [162]:
np.allclose([1e10,1e-8],[1.00001e10,1e-9])

True

In [163]:
np.array_equal([1e10,1e-8],[1.00001e10,1e-9])

False

#### immutable

In [164]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] =1

ValueError: assignment destination is read-only

####  转为极坐标 

In [165]:
Z = np.random.random((10,2))
X, Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.76068413 0.94941568 1.07345366 0.3561561  0.95645933 0.85972341
 0.69365479 0.55546626 1.12658193 0.17946829]
[0.18587016 1.14974027 0.47041928 1.26879207 0.50822781 1.46257827
 1.06305512 1.36655033 0.87654508 0.61387695]


In [166]:
Z = np.random.random(10)
Z[Z == Z.max()] = 0
Z

array([0.49055468, 0.02917956, 0.59486095, 0.20584548, 0.20280297,
       0.        , 0.06156638, 0.49923069, 0.24846698, 0.32714403])

In [180]:
Z[np.where(Z == Z.max())[0][0]] = 0
Z

array([0.49055468, 0.02917956, 0.        , 0.20584548, 0.20280297,
       0.        , 0.06156638, 0.        , 0.24846698, 0.32714403])

In [182]:
Z[Z.argmax()] = 0
Z

array([0.        , 0.02917956, 0.        , 0.20584548, 0.20280297,
       0.        , 0.06156638, 0.        , 0.24846698, 0.        ])

####  meshgrid

In [192]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [193]:
Z['x'] ,Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  矩阵计算

In [203]:
X = np.arange(5)
Y = np.arange(10,15)

In [208]:
C =1.0 /np.subtract.outer(X,Y)

In [212]:
np.linalg.det(C) #求行列式

-1.4030347488734904e-20

In [214]:
np.linalg.inv(C) # 求逆

array([[ -1261259.99997713,   3603599.99990542,  -3742199.99986698,
          1663199.99992304,   -264599.99998446],
       [  8408399.99997784, -23783759.99973727,  24393599.99948959,
        -10672199.99965114,   1663199.99992191],
       [-19819800.00018465,  55598400.00004967, -56453759.99948169,
         24393599.9994765 ,  -3742199.99986234],
       [ 19819800.00037285, -55212300.00058134,  55598400.00002613,
        -23783759.99971418,   3603599.99989927],
       [ -7157150.00018993,  19819800.00036616, -19819800.00016946,
          8408399.99996668,  -1261259.99997449]])

In [215]:
np.mat(np.linalg.inv(C))

matrix([[ -1261259.99997713,   3603599.99990542,  -3742199.99986698,
           1663199.99992304,   -264599.99998446],
        [  8408399.99997784, -23783759.99973727,  24393599.99948959,
         -10672199.99965114,   1663199.99992191],
        [-19819800.00018465,  55598400.00004967, -56453759.99948169,
          24393599.9994765 ,  -3742199.99986234],
        [ 19819800.00037285, -55212300.00058134,  55598400.00002613,
         -23783759.99971418,   3603599.99989927],
        [ -7157150.00018993,  19819800.00036616, -19819800.00016946,
           8408399.99996668,  -1261259.99997449]])

In [224]:
np.linalg.norm(C,1) #2范数

0.6456349206349207

In [222]:
np.linalg.norm(C,2)

0.5343573673480643

In [223]:
np.linalg.norm(C)

0.5344898177456043

####  各个类型的最大，最小

In [228]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [229]:
for dtype in [np.float32 , np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


####  显示设置

In [248]:
np.set_printoptions(threshold=sys.maxsize,edgeitems=2)
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [251]:
np.set_printoptions(precision=3,edgeitems=2,threshold=10)
Z = np.random.random((10,10))
Z

array([[0.374, 0.701, ..., 0.594, 0.152],
       [0.819, 0.16 , ..., 0.731, 0.812],
       ...,
       [0.034, 0.216, ..., 0.221, 0.438],
       [0.57 , 0.111, ..., 0.424, 0.344]])

####  close value

In [253]:
Z = np.arange(100)
V = np.random.uniform(0,100)
index = (np.abs(Z-V)).argmin()
Z[index]

11

In [256]:
Z = np.zeros(10,[('position',[('x',float,1),
                              ('y',float,1)]),
                ('color',    [('r',float,1),
                              ('g',float,1),
                              ('b',float,1)]),
                ])
Z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 数据在新的数据坐标的距离

In [261]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
Z

array([[0.586, 0.951],
       [0.247, 0.597],
       ...,
       [0.214, 0.152],
       [0.722, 0.716]])

In [268]:
D = np.sqrt((X-X.T)**2+(Y-Y.T)**2) #broard casting

In [269]:
import scipy
import scipy.spatial

In [270]:
Z = np.random.random((10,2))

In [273]:
D = scipy.spatial.distance.cdist(Z,Z)

In [274]:
D

array([[0.   , 0.689, ..., 0.674, 0.553],
       [0.689, 0.   , ..., 0.899, 1.054],
       ...,
       [0.674, 0.899, ..., 0.   , 0.369],
       [0.553, 1.054, ..., 0.369, 0.   ]])

####  dtype

In [276]:
Z = np.arange(10,dtype = np.float32)
Z = Z.astype(np.int32,copy = False)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [283]:
from io import StringIO
s = StringIO('''1,2,3,4,5\n
                6, , ,7,8\n
                , , 9,10,11\n''')

In [284]:
Z = np.genfromtxt(s,delimiter=',',dtype=np.int)
Z

array([[ 1,  2, ...,  4,  5],
       [ 6, -1, ...,  7,  8],
       [-1, -1, ..., 10, 11]])

####  enumerate

In [285]:
Z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [286]:
for index in np.ndindex(Z.shape):
    print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### Gaussian-like array 二维高斯数组

In [287]:
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))

In [291]:
Y == X

array([[ True, False, ..., False, False],
       [False,  True, ..., False, False],
       ...,
       [False, False, ...,  True, False],
       [False, False, ..., False,  True]])

In [293]:
D = np.sqrt(X*X + Y*Y)
D

array([[1.414, 1.267, ..., 1.267, 1.414],
       [1.267, 1.1  , ..., 1.1  , 1.267],
       ...,
       [1.267, 1.1  , ..., 1.1  , 1.267],
       [1.414, 1.267, ..., 1.267, 1.414]])

In [294]:
sigma,mu = 1.0,0.0
G = np.exp(-((D-mu)**2)/(2*sigma**2))
print(G)

[[0.368 0.448 ... 0.448 0.368]
 [0.448 0.546 ... 0.546 0.448]
 ...
 [0.448 0.546 ... 0.546 0.448]
 [0.368 0.448 ... 0.448 0.368]]


#### 随机替代p个元素

In [305]:
n = 10
P = 3
Z = np.zeros((n,n))
np.set_printoptions(threshold = sys.maxsize)
np.put(Z,np.random.choice(range(n*n),P,replace = False),1)
Z

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [311]:
np.random.choice(range(n*n),10,replace = False)

array([82, 18, 45, 86, 53, 75, 81, 61, 89, 48])

#### Mean

In [328]:
X = np.random.randn(5,10)
print(X)
Y = X - X.mean(axis = 1,keepdims = True)
Y

[[ 9.336e-01  6.101e-01 -2.312e-02  1.597e+00  1.009e+00  1.043e+00
   2.943e-01  1.647e-02  1.098e+00  9.876e-01]
 [ 1.841e-01 -2.246e-01  4.792e-01 -9.393e-01 -1.079e-01  6.044e-01
  -1.239e+00 -8.721e-01  7.209e-01 -2.385e-01]
 [-4.255e-02 -1.865e+00 -8.199e-01  1.676e-01 -1.195e+00 -6.609e-01
  -2.868e-01  2.381e-01 -1.249e+00 -3.081e-01]
 [ 1.496e+00 -1.963e-01  2.533e-01  4.696e-01  1.122e+00  1.647e+00
   3.190e-01 -1.067e+00  6.243e-01 -3.446e-01]
 [-7.412e-01 -6.462e-01 -1.294e+00  5.824e-01  1.673e+00 -1.837e-01
   1.368e+00 -8.266e-01 -5.826e-04 -3.591e-01]]
[ 0.757 -0.163 -0.602  0.432 -0.043]


array([[ 0.177, -0.147, -0.78 ,  0.84 ,  0.253,  0.287, -0.462, -0.74 ,
         0.342,  0.231],
       [ 0.347, -0.061,  0.643, -0.776,  0.055,  0.768, -1.076, -0.709,
         0.884, -0.075],
       [ 0.56 , -1.263, -0.218,  0.77 , -0.593, -0.059,  0.315,  0.84 ,
        -0.647,  0.294],
       [ 1.064, -0.629, -0.179,  0.037,  0.69 ,  1.215, -0.113, -1.499,
         0.192, -0.777],
       [-0.698, -0.603, -1.251,  0.625,  1.716, -0.141,  1.411, -0.784,
         0.042, -0.316]])

In [339]:
print(X.mean(axis = 1,keepdims = False))

[ 0.757 -0.163 -0.602  0.432 -0.043]


In [340]:
print(X.mean(axis = 1,keepdims = True))

[[ 0.757]
 [-0.163]
 [-0.602]
 [ 0.432]
 [-0.043]]


In [331]:
X.mean(axis = 1).reshape(-1,1)

array([[ 0.757],
       [-0.163],
       [-0.602],
       [ 0.432],
       [-0.043]])

In [332]:
X -X.mean(axis = 1).reshape(-1,1)

array([[ 0.177, -0.147, -0.78 ,  0.84 ,  0.253,  0.287, -0.462, -0.74 ,
         0.342,  0.231],
       [ 0.347, -0.061,  0.643, -0.776,  0.055,  0.768, -1.076, -0.709,
         0.884, -0.075],
       [ 0.56 , -1.263, -0.218,  0.77 , -0.593, -0.059,  0.315,  0.84 ,
        -0.647,  0.294],
       [ 1.064, -0.629, -0.179,  0.037,  0.69 ,  1.215, -0.113, -1.499,
         0.192, -0.777],
       [-0.698, -0.603, -1.251,  0.625,  1.716, -0.141,  1.411, -0.784,
         0.042, -0.316]])

#### 排序

In [341]:
Z = np.random.randint(0,10,(3,3))
Z

array([[5, 1, 8],
       [0, 3, 2],
       [6, 1, 3]])

In [342]:
Z[Z[:,1].argsort()]

array([[5, 1, 8],
       [6, 1, 3],
       [0, 3, 2]])

In [360]:
Z = np.random.randint(0,3,(3,10))
Z

array([[2, 0, 1, 1, 0, 2, 2, 2, 0, 2],
       [0, 2, 2, 2, 2, 2, 0, 1, 2, 1],
       [1, 2, 1, 0, 2, 2, 0, 1, 1, 2]])

In [346]:
z = 0.5

In [350]:
m = Z.flat[np.abs(Z-z).argmin()]

In [351]:
m

1

In [354]:
np.abs(Z-z)

array([[1.5, 1.5, 0.5, 0.5, 1.5, 1.5, 1.5, 0.5, 1.5, 1.5],
       [1.5, 0.5, 1.5, 0.5, 1.5, 1.5, 0.5, 1.5, 0.5, 1.5],
       [0.5, 0.5, 1.5, 0.5, 0.5, 0.5, 1.5, 0.5, 1.5, 0.5]])

In [355]:
np.abs(Z-z).argmin()

2

In [363]:
Z.flat[10]
# z.flatten

0

#### iter

In [381]:
A = np.random.randn(3)
B = np.random.randn(3,1)
np.sum(B.T +A)

4.333947155014582

In [383]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
[i for i in it]

[(array(0), array(0), array(3690198956322732578)),
 (array(0), array(1), array(7293640499924186681)),
 (array(0), array(2), array(4063435642958723173)),
 (array(1), array(0), array(3906650808252446521)),
 (array(1), array(1), array(7863896424725100386)),
 (array(1), array(2), array(2478510836883089267)),
 (array(2), array(0), array(8319683848551211578)),
 (array(2), array(1), array(7958535038077905954)),
 (array(2), array(2), array(7308253928395992417))]

In [384]:
for x,y,z in it: z[...] = x + y

In [385]:
it.operands[2]

array([[3690198956322732578, 7293640499924186681, 4063435642958723173],
       [3906650808252446521, 7863896424725100386, 2478510836883089267],
       [8319683848551211578, 7958535038077905954, 7308253928395992417]])

In [387]:
it = np.nditer([A,B])
[i for i in it]

[(array(0), array(0)),
 (array(0), array(1)),
 (array(0), array(2)),
 (array(1), array(0)),
 (array(1), array(1)),
 (array(1), array(2)),
 (array(2), array(0)),
 (array(2), array(1)),
 (array(2), array(2))]

In [388]:
for x,y,z in it: z[...] = x + y

In [392]:
it.operands[1]

array([[0, 1, 2]])