#### 矩阵向量积

##### dot

In [11]:
np.dot(3,2)

6

In [12]:
np.dot([1,2],[4,8])

20

In [14]:
a=np.arange(4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
np.dot(a,b)

array([[ 6,  7],
       [26, 31]])

In [15]:
a@b

array([[ 6,  7],
       [26, 31]])

In [24]:
a=np.arange(6).reshape(2,3)
print(a)
b=[1,2,3]
np.dot(a,b)

[[0 1 2]
 [3 4 5]]


array([ 8, 26])

In [26]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a,b).shape

(3, 4, 5, 5, 4, 3)

##### vdot

In [28]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
np.vdot(a, b)

30

In [30]:
1*4+4*1+2*5+2*6

30